export const STRAVA_AUTH_START  = "STRAVA_AUTH_START";
export const STRAVA_AUTH_TOKEN_VALIDATED = "STRAVA_AUTH_TOKEN_VALIDATED";
export const STRAVA_AUTH_TOKEN_UPDATE = "STRAVA_AUTH_TOKEN_UPDATE";
export const STRAVA_AUTH_LOG_OUT = "STRAVA_AUTH_LOG_OUT";